// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyNC5VOrJdQRvkhdS1jGm-qntZ8U8o97E',
    appId: '1:255709079796:web:69770d0bcfb2ed9c6916a1',
    messagingSenderId: '255709079796',
    projectId: 'arts-nails',
    authDomain: 'arts-nails.firebaseapp.com',
    storageBucket: 'arts-nails.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFpC7KR4S6zGP2EV9dqhALqqk9fD451k',
    appId: '1:255709079796:android:a3a7faadeb8579ad6916a1',
    messagingSenderId: '255709079796',
    projectId: 'arts-nails',
    storageBucket: 'arts-nails.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh88fDDUjFHNBd1nquGnK32SpXAfnw_jI',
    appId: '1:255709079796:ios:5e63e5240ba188986916a1',
    messagingSenderId: '255709079796',
    projectId: 'arts-nails',
    storageBucket: 'arts-nails.appspot.com',
    iosBundleId: 'com.example.artsNails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh88fDDUjFHNBd1nquGnK32SpXAfnw_jI',
    appId: '1:255709079796:ios:587a96b22282999d6916a1',
    messagingSenderId: '255709079796',
    projectId: 'arts-nails',
    storageBucket: 'arts-nails.appspot.com',
    iosBundleId: 'com.example.artsNails.RunnerTests',
  );
}
